### PR TITLE
Added controller support

### LINKED ISSUE #1: Unable to fill newly placed casks with controller
Using SMAPI 2.4 with Stardew Valley 1.2.33 on Unix 4.15.2.2, CasksAnywhere 1.1-alpha

It seems casks that are already placed when the mod is loaded are able to be filled, but casks that you place after the mod loads are not able to be filled and returns a "Can only be used in Cellar" notification.

How to reproduce:

1. Start SD w/ SMAPI & CasksAnywhere
2. Place a new cask
3. Try to fill it
4. Receive "Can only be used in Cellar" notification.

Other mods used while bug occurred:

- Range Display 1.1.1 by Cat

Testing workaround:

- Reloading area does nothing
- Sleeping does nothing
- Sleeping then restarting the game works, but is a bad workaround

On further inspection it seems this only happens when the user uses a gamepad controller.

### PR DESCRIPTION
**Pull request by Necklaces**
Fixes #1

### CODE REVIEW

**Comment by LeonBlade** [comment]
Hey, thank you for taking the time to report an issue and fix it.  I wasn't aware of this issue, even being a controller user myself.  I feel like I did write code similar to what you added here, but clearly I never did.  I'll go ahead and merge and put out a new release.

Thanks!

**Comment by LeonBlade** [comment]
Unfortunately, I'm busy for the next few hours, I'll get back to this then.

**Comment by Necklaces** [comment]
@LeonBlade Don't worry about it and no problem! I meant to write this earlier but was caught in the game.

I play using a ps3 sixaxis controller and recently found out casks didn't work outside the cellar, so I got into SMAPI and found your mod, thanks for making it! But then when I booted it up I found it didn't work so I decided to spend some time figuring out how to build on Linux (which was a journey in itself), and then look into the code. At first I thought maybe it had something to do with the mod not hijacking other then when it first started, but after starting to switch the code a bit and testing with a mouse & keyboard I was surprised to find that it now worked! 

Looking closer I found the `Hijack(Game1.currentLocation, Game1.currentCursorTile);` line, and thought "Cursor.. huh..", so naturally I tried changing that to `Hijack(Game1.currentLocation, Game1.player.GetGrabTile());` but it still didn't work!

I found some code in the discord that suggested maybe doing something like this to get the tile instead:

```
Vector2 tile = Game1.currentCursorTile;
    tile = Utility.tileWithinRadiusOfPlayer((int)tile.X, (int)tile.Y, 1, Game1.player)
        ? tile
        : Game1.player.GetGrabTile();
```

But that _still_ didn't work, so I started printing coordinates from both `currentCursorTile` and `GetGrabTile()` as I tested with both mouse and keyboard.

What I found was that it always hijacked the casks using mouse & keyboard, but it would not hijack the casks I placed with a controller. When in use, the controller only seemed to "hide" the cursor, and that was what would get returned, so I thought maybe first try `currentCursorTile` and then if that doesn't work try `GetGrabTile()`, but then it only worked sometimes!

In fact, I was surprised to find that very often `GetGrabTile()` wouldn't get the correct tile!

I managed to boil it down to this: if the player is standing in between two tiles, the placement tile will be "two" tiles further ahead rather than one, and `GetGrabTile()` only returns the one in front of the player. Only when standing completely in the middle of a tile will grabTile be correct.

between

close

So I thought whatever, let's just check every cask, but then every time the player places a cask it reset or (re)hijacked all the casks in the location (very visible as it reset the animation, and it lagged the entire cellar), adding the check for `is HijackCask` fixed that. 

There's probably a better fix, maybe if there's a way to get the exact tile location from the placed `e.Removed` item `OnInventoryChanged` the code wouldn't need to loop through all items in the location/scene, but I couldn't figure that out.

Either way, thanks for the mod and thanks for merging!

**Comment by LeonBlade** [comment]
I thought that's what my Hijack method was supposed to do, which is why I wrote it.  Maybe I never committed it or something, I have no idea.

I'll be creating the releases now for your merge.  Thanks again!

**Pull request merged**
